<section id="random" class="container">
    <h1 class="text-light">Randomizer SMITE</h1>
    <div class="row justify-content-center">
        <div id="god">
            <p class="god_name text-light"><?= htmlspecialchars($god['name']) ?></p>
            <p class="god_title text-light"><?= htmlspecialchars($god['title']) ?></p>
            <img onmouseover="montre('<?php echo (htmlspecialchars($god['description'])); ?>')" onmouseout="cache()" class="god_picture" src="<?= htmlspecialchars($god['picture_god']) ?>">


        </div>
        <div id="items">
            <?php while ($items = $query_items->fetch()) : ?>
                <div class="item">
                    <p class="item_name text-light"><?= htmlspecialchars($items['name']) ?></p>
                    <img onmouseover="montre('<?php if (!empty($items['passif'])) {
                                                    echo (htmlspecialchars($items['passif']));
                                                } else {
                                                    echo ("Cet objet n\'a pas de passif");
                                                } ?>')" onmouseout="cache()" class="item_picture" src="<?= htmlspecialchars($items['picture_item']) ?>">
                </div>

            <?php endwhile ?>
        </div>
        <div class="container">
            <a href=""><button class="randomize-button col-sm-2">Randomize</button></a>
        </div>
    </div>

</section>