<div class="container">
    <div class="m-5">
        <form action="login.php" method="post">
            <fieldset>
                <h1>Se connecter</h1>
                <?= $message ?>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" id="email" class="form-control">
                </div>

                <div class="mb-3">
                    <label for="pass" class="form-label">Mot de passe</label>
                    <input type="password" name="pass" id="pass" class="form-control">
                </div>
            </fieldset>
            <input type="submit" value="Envoyer">
        </form>
    </div>
</div>