<div class="container bg-light">
    <div class="m-5 row">
        <form action="./login" method="post">
            <fieldset>
                <h1>Se connecter</h1>
                <?= $message ?>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <div class="col-sm-5">
                        <input value="l.lecomte77@gmail.com" type="email" name="email" id="email" class="form-control fs-4">
                    </div>
                </div>
                <div class="mb-3">
                    <div class="col-sm-5">
                        <label for="pass" class="form-label">Mot de passe</label>
                        <input value="123456" type="password" name="pass" id="pass" class="form-control fs-4">
                    </div>
                </div>
            </fieldset>
            <input type="submit" value="Envoyer">
        </form>
    </div>
</div>